AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        CORS_ORIGIN: !Ref CorsOrigin

Parameters:
  CorsOrigin:
    Type: String
    Default: "*"
    Description: CORS origin for API Gateway

Resources:
  # DynamoDB table for session management
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: screen-share-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # API Gateway
  ScreenShareApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: !Ref CorsOrigin

  # Lambda function for creating sessions
  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: createSession.handler
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        CreateSession:
          Type: Api
          Properties:
            RestApiId: !Ref ScreenShareApi
            Path: /session
            Method: post

  # Lambda function for WebRTC signaling
  SignalingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: signaling.handler
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
      Events:
        Signaling:
          Type: Api
          Properties:
            RestApiId: !Ref ScreenShareApi
            Path: /signaling/{sessionId}
            Method: post

  # S3 bucket for hosting frontend
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-website-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ScreenShareApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  WebsiteURL:
    Description: "CloudFront URL"
    Value: !GetAtt CloudFrontDistribution.DomainName